Repository dhbw-stuttgart-webengineering/programmentwurf-gruppe-1, pull requests merged in 2023-11, with the labels that each got.

#43 Improve Password Encryption
  .env.example
  apps/authentication/views.py
  apps/data_endpoint/views.py
Labels: core

#44 Code Improvements
  apps/authentication/models.py
  apps/data_endpoint/urls.py
  apps/data_endpoint/views.py
  apps/templates/home/index.html
  apps/templates/home/loading.html
  apps/templates/home/page-404.html
  apps/templates/layouts/base-fullscreen.html
Labels: bug

#51 Improve Code Structure and Comments
  apps/authentication/__init__.py
  apps/authentication/admin.py
  apps/authentication/config.py
  apps/authentication/forms.py
  apps/authentication/views.py
  apps/data_endpoint/views.py
  apps/home/__init__.py
  apps/home/admin.py
  apps/home/config.py
  apps/home/models.py
  apps/home/tests.py
  apps/home/urls.py
  apps/home/views.py
  apps/utils/dualis/dualis_session.py
  apps/utils/dualis/webscraper.py
  core/settings.py
Labels: enhancement

#52 Removes access to html files in home
  apps/home/views.py
Labels: bug

#59 Add integrity check
  .github/dependabot.yml
  apps/templates/includes/scripts.html
Labels: bug

#71 Überarbeitung mit Bootstrap
  apps/authentication/forms.py
  apps/data_endpoint/views.py
  apps/static/css/bootstrap-grid.min.css
  apps/static/css/bootstrap-utilities.min.css
  apps/static/css/bootstrap.css
  apps/static/css/bootstrap.min.css
  apps/static/css/pico.min.css
  apps/static/css/pico.min.css.map
  apps/static/js/bootstrap-theme-switcher.js
  apps/static/js/bootstrap.bundle.min.js
  apps/static/js/bootstrap.js
  apps/static/js/bootstrap.min.js
  apps/static/js/loading.js
  apps/static/js/minimal-theme-switcher.js
  apps/templates/accounts/login.html
  apps/templates/home/index.html
  apps/templates/home/loading.html
  apps/templates/includes/scripts.html
  apps/templates/layouts/base-fullscreen.html
  core/urls.py
Labels: enhancement

#66 Fix start.sh to auto-collect staticfiles
  start.sh
Labels: bug

#73 Sitemap
  apps/home/urls.py
  apps/home/views.py
  apps/static/robots.txt
  apps/static/sitemap.xml
Labels: enhancement

#80 add method to calculate students average
  apps/data_endpoint/calculate_average.py
  apps/home/views.py
Labels: core

#82 Add guest login functionality and improve UI
  apps/static/js/loading.js
  apps/templates/accounts/login.html
Labels: enhancement

#84 Remove unused jQuery and fix login form layout
  apps/templates/accounts/login.html
  apps/templates/includes/scripts.html
Labels: enhancement
